### ISSUE TITLE
composer.json and target-dir failure

### ISSUE THREAD

**Issue by tautelis** [oroinc/redis-config#14]
Hello,

recent updates broke composer autoloader:

```
app/console oro:install --env=prod
PHP Fatal error:  Uncaught Error: Class 'Oro\Bundle\RedisConfigBundle\OroRedisConfigBundle' not found in /home/project/src/app/cache/prod/bundles.php:17
```

It is due to `src/` part in `target-dir` option at composer.json since directories must represent missing root namespace.

Furthermore, why don't you use PSR-4 ?

**Comment by RocKordier** [comment]
Hope we can speed up this request through OSD-1776 :)
Thx Eric

**Comment by bemzaslava** [comment]
https://github.com/oroinc/redis-config/pull/15#issuecomment-365271779
