### ISSUE TITLE
Store sessions in Redis

### ISSUE THREAD

**Issue by devzorg** [oroinc/redis-config#2]
Parameter redis_dsn_session doesn't help to save sessions to redis

oro/crm 1.9.1
oro/redis-config 1.2

**Comment by RocKordier** [comment]
Hey @devzorg,

please have a look to the [SncRedisBundle documentation](https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md#sessions)!

You need to add `framework.session.handler_id: snc_redis.session.handler` to your config.yml

For me everything is working as expected.

**Comment by serhiicherepanov** [comment]
@devzorg Hi, thanks  for your help! 
Your changes merged to 2.0 version
