### ISSUE TITLE
SNC version

### ISSUE THREAD

**Issue by LRotherfield** [oroinc/redis-config#7]
Hi guys

Is there a specific reason that this bundle is using 1.1.x-dev of the snc/redis bundle and not 2.0?

I was running the 2.0.0-rc1 version of oro platform fine but in the last 10 days, a requirement for this bundle was added https://github.com/orocrm/platform/commit/62371cfed0de443cf57df15aa693ce19ac8b73e0

Cheers
Luke

**Comment by mkudelya** [comment]
Hi

I think because at the moment we don't have plans to switch snc/redis to 2.0.

**Comment by LRotherfield** [comment]
Hi @mkudelya 

What are your reasons for not updating to 2.0.0?  It is the recommended branch for Symfony2.7+ and the only branch that will work with Symfony3.

**Comment by mkudelya** [comment]
Hi @LRotherfield 

I have read 2.0 [UPDATE.md](https://github.com/snc/SncRedisBundle/blob/master/UPDATE.md#200) and this version are fairly minor changes. We now have quite a busy schedule and i think we will consider this update when we move to the next major version of symfony.

**Comment by alex-n-2k7** [comment]
@LRotherfield,  I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
